jobs:
  hadolint-callback:
    name: Lint callback Dockerfile
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Pull HaDoLint image
      run: docker pull hadolint/hadolint
    - continue-on-error: true
      name: Lint callback Dockerfile
      run: docker run --rm --interactive hadolint/hadolint hadolint --ignore DL3059
        - < ./services/callback/Dockerfile
  hadolint-distribution:
    name: Lint distribution Dockerfile
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Pull HaDoLint Image
      run: docker pull hadolint/hadolint
    - continue-on-error: true
      name: Lint distribution Dockerfile
      run: docker run --rm --interactive hadolint/hadolint hadolint --ignore DL3059
        - < ./services/distribution/Dockerfile
  hadolint-download:
    name: Lint download Dockerfile
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Pull HaDoLint Image
      run: docker pull hadolint/hadolint
    - continue-on-error: true
      name: Lint download Dockerfile
      run: docker run --rm --interactive hadolint/hadolint hadolint --ignore DL3059
        - < ./services/download/Dockerfile
  hadolint-submission:
    name: Lint submission Dockerfile
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Pull HaDoLint Image
      run: docker pull hadolint/hadolint
    - continue-on-error: true
      name: Lint submission Dockerfile
      run: docker run --rm --interactive hadolint/hadolint hadolint --ignore DL3059
        - < ./services/submission/Dockerfile
  hadolint-upload:
    name: Lint upload Dockerfile
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Pull HaDoLint Image
      run: docker pull hadolint/hadolint
    - continue-on-error: true
      name: Lint upload Dockerfile
      run: docker run --rm --interactive hadolint/hadolint hadolint --ignore DL3059
        - < ./services/upload/Dockerfile
name: hadolint-analysis-workflow
on:
  repository_dispatch:
    types: trigger-ga___hadolint-analysis.yml
