jobs:
  mvn-verify:
    name: run mvn verify and do SonarCloud scan
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: mvn verify
      run: mvn -B -P integration-test verify --fail-fast --file pom.xml -Dorg.slf4j.simpleLogger.defaultLogLevel=warn
    - continue-on-error: true
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      name: SonarCloud scan
      run: mvn -B sonar:sonar --fail-never -Dorg.slf4j.simpleLogger.defaultLogLevel=warn
    - continue-on-error: true
      if: always()
      name: Report JUnit results at checks
      uses: dorny/test-reporter@v1
      with:
        fail-on-error: true
        list-suites: failed
        list-tests: failed
        name: Maven Tests
        path: '**/surefire-reports/*.xml'
        reporter: java-junit
    - continue-on-error: true
      if: always()
      name: Report JUnit results at checks as comment
      uses: EnricoMi/publish-unit-test-result-action/composite@v1
      with:
        files: '**/surefire-reports/*.xml'
name: maven-build
on:
  repository_dispatch:
    types: trigger-ga___maven-build.yml
permissions:
  checks: write
  pull-requests: write
  statuses: write
